# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_version = 0.5+1.20.5
maven_group = com.github.zly2006
archives_base_name = come-back-my-villagers

# Fabric Properties
# check these on https://modmuss50.me/fabric.html

minecraft_version=24w13a
yarn_mappings=24w13a+build.6
loader_version=0.15.7

#Fabric api
fabric_version=0.96.13+1.20.5
